# Generated by Django 4.1.3 on 2022-11-28 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("simplegis", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
