# Generated by Django 4.1.3 on 2022-12-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simplegis", "0011_alter_busstop_options_alter_house_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="address",
            field=models.CharField(max_length=200, verbose_name="адрес"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(max_length=200, verbose_name="название"),
        ),
    ]
