x-services:
  drf: &drf
    build:
      context: .
      dockerfile: Dockerfile
    image: backend

version: "3.8"

services:
  backend:
    <<: *drf
    container_name: geo_back
    command: gunicorn --bind 0.0.0.0:8000 --workers 2 geo_back.wsgi:application
    restart: always
    volumes:
      - ./geo_back/: ./geo_back/
    expose:
      - "8000"
    ports:
      - "8090:8000"
    networks:
      - geo-network
    depends_on:
      - postgres

  job_migrate:
    <<: *drf
    command: python manage.py migrate

  db:
    container_name: geo_postgres
    image: postgis/postgis:16-3.4-alpine
    restart: always
    environment:
      LC_ALL: C.UTF-8
      PASSWORD: ${DB_PASSWORD}
      DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data/
      - db-conf:/etc/postgresql
      - db-logs:/var/log/postgesql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - geo-network
    ports:
      - "54320:5432"

