# Generated by Django 4.1.3 on 2022-12-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplegis', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='House',
        ),
    ]
