# Generated by Django 4.1.3 on 2022-12-01 17:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplegis', '0004_rename_test_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfStation', models.CharField(max_length=400)),
                ('Line', models.CharField(max_length=400)),
                ('IncomingPassangers', models.PositiveIntegerField()),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
