# Generated by Django 4.1.3 on 2022-12-03 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplegis', '0008_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstop',
            old_name='StationName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='busstop',
            old_name='RouteNumbers',
            new_name='route_numbers',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='address_new',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='metro',
            old_name='IncomingPassengers',
            new_name='incomingpassengers',
        ),
        migrations.RenameField(
            model_name='metro',
            old_name='Line',
            new_name='line',
        ),
        migrations.RenameField(
            model_name='metro',
            old_name='NameOfStation',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='Sales',
            new_name='sales',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='Square',
            new_name='square',
        ),
    ]
